### ISSUE TITLE
Can it support cloud connectivity?

### ISSUE THREAD

**Issue by Carl19** [za-wa-n-go/ComfyUI_Zwng_Nodes#4]
Thank you for developing this plugin.
I am a Mac and the local usage is slow. Can there be a place to fill in the URL so that this plugin can also be used on the GPU platform?

**Comment by za-wa-n-go** [comment]
Thank you for using the service! However, since I am a beginner using GPT, it's difficult to handle. 
If it's a PhotoShop node, the following might be better.
https://github.com/NimaNzrii/comfyui-photoshop
